export enum PermissionEnum {
  SYSTEM_ADMIN = 'system_admin',
  VIEW_TRANSFERS = 'view_transfers',
  CREATE_TRANSFER = 'create_transfer',
  EDIT_TRANSFER = 'edit_transfer',
  DELETE_TRANSFER = 'delete_transfer',
  VIEW_VEHICLES = 'view_vehicles',
  CREATE_VEHICLE = 'create_vehicle',
  EDIT_VEHICLE = 'edit_vehicle',
  DELETE_VEHICLE = 'delete_vehicle',
  VIEW_PROJECTS = 'view_projects',
  CREATE_PROJECT = 'create_project',
  EDIT_PROJECT = 'edit_project',
  DELETE_PROJECT = 'delete_project',
  VIEW_ORGANIZATIONAL_UNITS = 'view_organizational_units',
  CREATE_ORGANIZATIONAL_UNIT = 'create_organizational_unit',
  EDIT_ORGANIZATIONAL_UNIT = 'edit_organizational_unit',
  DELETE_ORGANIZATIONAL_UNIT = 'delete_organizational_unit',
  PROFILE_VIEW = 'profile:view',
}